### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_sections'

### ISSUE THREAD

**Issue by iljah** [vsoch/helpme#25]
Updated to latest version in pip from few minutes ago and tried to submit issue to this repo:
```
Traceback (most recent call last):
  File ".../.local/bin/helpme", line 11, in <module>
    load_entry_point('helpme==0.0.31', 'console_scripts', 'helpme')()
  File ".../.local/lib/python3.6/site-packages/helpme/client/__init__.py", line 150, in main
    main(args, extras)
  File ".../.local/lib/python3.6/site-packages/helpme/client/help.py", line 44, in main
    helper.run(positionals=extras)
  File ".../.local/lib/python3.6/site-packages/helpme/main/base/__init__.py", line 88, in run
    steps = self.config._sections[self.name]
AttributeError: 'NoneType' object has no attribute '_sections'
```

**Comment by vsoch** [comment]
Did you do pip install helpme[all] ?

**Comment by iljah** [comment]
install helpme[all] only listed a bunch of satisfied dependencies.

**Comment by iljah** [comment]
When trying with uservoice I instead get:
```
Traceback (most recent call last):
  File ".../.local/bin/helpme", line 11, in <module>
    load_entry_point('helpme==0.0.31', 'console_scripts', 'helpme')()
  File ".../.local/lib/python3.6/site-packages/helpme/client/__init__.py", line 150, in main
    main(args, extras)
  File ".../.local/lib/python3.6/site-packages/helpme/client/help.py", line 38, in main
    helper = get_helper(name)
  File ".../.local/lib/python3.6/site-packages/helpme/main/__init__.py", line 50, in get_helper
    return Helper()
  File ".../.local/lib/python3.6/site-packages/helpme/main/uservoice/__init__.py", line 32, in __init__
    super(Helper, self).__init__(**kwargs)
  File ".../.local/lib/python3.6/site-packages/helpme/main/base/__init__.py", line 55, in __init__
    self.load_secrets()
  File ".../.local/lib/python3.6/site-packages/helpme/main/uservoice/__init__.py", line 43, in load_secrets
    setting = self._get_and_update_setting(envar, user=False)
  File ".../.local/lib/python3.6/site-packages/helpme/main/base/settings.py", line 201, in get_and_update_setting
    setting = self._get_setting(name, user=user)
  File ".../.local/lib/python3.6/site-packages/helpme/main/base/settings.py", line 137, in get_setting
    if section in config:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by vsoch** [comment]
Both of these are because the helpme.cfg isn't found and loaded from your home! I will fix this up tomorrow, it's just after midnight here now so I should be off to bed :-)

**Comment by iljah** [comment]
Installing from checked out repository worked but pip installation would be nice to fix since it fetches dependencies automatically. And after that install from repo is also easy...

**Comment by vsoch** [comment]
hey @iljah can you give me the exact steps to reproduce this? I have generated the error once on my own (and thought it would be trivial) but I can't seem to do it now. Thank you!

It also looks like pip install helpme should be the same as pip install helpme[all], apologies for the bad advice :)

**Comment by iljah** [comment]
This (doesn't) works is to:
- `pip3 uninstall helpme`
- `pip3 install helpme --user`
- `.local/bin/helpme github`
which gives
```
ERROR You must export HELPME_GITHUB_TOKEN to use Github
https://vsoch.github.io/helpme/helper-github
```
after which export HELPME_GITHUB_TOKEN=... and running helpme again gives above most error.

**Comment by vsoch** [comment]
okay just reproduced! It must be something about the --user install, let me look into it.

**Comment by iljah** [comment]
Hmm looking at pypi, latest version seems to be 1.0 but from 2016, that doesn't look right: https://pypi.org/project/helpme/

**Comment by vsoch** [comment]
It's definitely not! I just deleted it. Was that the issue?

**Comment by vsoch** [comment]
I don't think so, at least for me it installed the version 0.0.32 that I was expecting. I wonder why the (higher) version wasn't used? Oh well, it's removed so hopefully not an issue anymore. This was a result of me releasing a first go as version 1.0 and then changing my mind to start with lower numbers (anticipating more changes like this).

**Comment by iljah** [comment]
Still getting top most error with 0.0.32.

**Comment by vsoch** [comment]
okay I found the root of the bug! When installed by the user and going into .local, the configfile isn't added to where it is expected:

```bash
Out[25]: '/home/vanessa/.local/lib/python3.6/site-packages/helpme/helpme.cfg'
In [26]: os.path.exists(configfile)
False
```

**Comment by vsoch** [comment]
okay I think I fixed this up! The distribution was missing a MANIFEST.in, but then also I needed to (not specify the data files twice) with the MANIFEST AND in the setup.py. I just pushed a new version here and to pypi, and it looks like the file is now included:

```bash
pip3 install helpme --user
...
Installing collected packages: helpme
  The script helpme is installed in '/home/vanessa/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed helpme-0.0.35

 ls /home/vanessa/.local/lib/python3.6/site-packages/helpme/
action  client  defaults.py  helpme.cfg  __init__.py  logger  main  __pycache__  utils  version.py
```
```bash
$ /home/vanessa/.local/bin/helpme github
[helpme|github]
Hello Friend! I'll help you post a Github issue today.
What is the Github repository to post to? (e.g., username/reponame): 
```

Do you want to give it another go, and I'll cross my fingers? :L)

**Comment by vsoch** [comment]
:D
