### ISSUE TITLE
Discourse helper needs to mkdir first

### ISSUE THREAD

**Issue by vsoch** [vsoch/helpme#42]
```
Traceback (most recent call last):
  File "/opt/conda/bin/helpme", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/helpme/client/__init__.py", line 148, in main
    main(args, extras)
  File "/opt/conda/lib/python3.7/site-packages/helpme/client/help.py", line 38, in main
    helper = get_helper(name=name)
  File "/opt/conda/lib/python3.7/site-packages/helpme/main/__init__.py", line 48, in get_helper
    return Helper()
  File "/opt/conda/lib/python3.7/site-packages/helpme/main/discourse/__init__.py", line 39, in __init__
    self._generate_keys()
  File "/opt/conda/lib/python3.7/site-packages/helpme/main/discourse/__init__.py", line 93, in _generate_keys
    self.key = generate_keypair(self.keypair_file)           
  File "/opt/conda/lib/python3.7/site-packages/helpme/utils/settings.py", line 72, in generate_keypair
    with open(keypair_file, 'wb') as filey:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.helpme/discourse/private.pem'
```

**Comment by vsoch** [comment]
Fixed with #43
